services:
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - type: bind
        source: ./backend/app
        target: /app

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - type: bind
        source: ./frontend/app
        target: /app
      - type: volume
        source: node_modules
        target: /app/node_modules
      - type: volume
        source: .svelte-kit
        target: /app/.svelte-kit
    depends_on:
      - backend

volumes:
  .svelte-kit:
  node_modules:
